image: ruby:2.3
stages:
  - deploy

before_script:
  - gem install bundler

deploy_site:
  stage: deploy
  only:
    - master
  script:
    - export LANG=en_US.UTF-8
    - bundle install --path=vendor/
    - bundle exec jekyll build --future # The server is in another timezone..
  artifacts:
    paths:
      - _site/

