language: ruby
rvm:
- 2.3.1

script:
    - export LANG=en_US.UTF-8
    - bundle install --path=vendor/
    - bundle exec jekyll build --future

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false 

